language: android
jdk: oraclejdk8
sudo: false
android:
    components:
        - tools
        - build-tools-24.0.1
        - android-24
        - extra-android-m2repository
script:
    - cd pretixdroid
    - TERM=dumb ./gradlew check lint assembleDebug
    - cat /home/travis/build/pretix/pretixdroid/pretixdroid/app/build/outputs/lint-results-debug.xml
cache:
    directories:
        - $HOME/.gradle
